default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: cloudops_dev
  pool: 10

staging:
  <<: *default
  database: cloudops_staging

test:
  <<: *default
  database: cloudops_testing_new
